name: Robot Framework with Requests Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Instala o Python e bibliotecas
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 3. Instala Robot Framework e outras bibliotecas
      - name: Install Robot Framework and Libraries
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests  # Instala o RF Requests para testes de API
          pip install -r requirements.txt  # Se houver mais dependências

      # 4. Executa os testes do Robot Framework
      - name: Run Robot Framework Tests
        run: |
          robot tests/

      # 5. Publica os resultados dos testes
      - name: Archive Robot Framework Results
        uses: actions/upload-artifact@v2
        with:
          name: robot-results
          path: output.xml
