name: API Robot Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.x'

    - name: Install Robot Framework and Libraries
      run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests  
          pip install -r requirements.txt  
      # 4. Executa os testes do Robot Framework
    - name: Run Robot Framework Tests
      run: |
          robot tests/
      # 5. Publica os resultados dos testes
    - name: Archive Robot Framework Results
      uses: actions/upload-artifact@v3
      with:
          name: robot-results
          path: output.xml

